# Generated by Django 2.1.2 on 2018-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181231_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
