# Generated by Django 2.1.2 on 2019-01-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190101_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_body',
            field=models.TextField(),
        ),
    ]
