# Generated by Django 2.1.2 on 2019-01-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190101_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_date',
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
