# Generated by Django 2.1.2 on 2019-01-01 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190101_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 10, 59, 37, 107614, tzinfo=utc)),
        ),
    ]
