# Generated by Django 2.1.2 on 2019-01-01 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190101_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 11, 25, 5, 868379, tzinfo=utc)),
        ),
    ]
