# Generated by Django 2.1.2 on 2019-01-01 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 18, 28, 9, 415498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
