# Generated by Django 2.1.2 on 2019-01-01 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190102_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 19, 16, 22, 216522, tzinfo=utc)),
        ),
    ]
