# Generated by Django 2.1.2 on 2019-01-02 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 5, 11, 80257, tzinfo=utc)),
        ),
    ]
