# Generated by Django 2.1.2 on 2019-01-02 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190102_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categori',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 2, 8, 13, 13, 484405, tzinfo=utc)),
        ),
    ]
