# Generated by Django 2.1.2 on 2019-03-15 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190103_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 14, 58, 30, 557199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\win10\\Desktop\\Blog_site\\media'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 14, 58, 30, 557199, tzinfo=utc)),
        ),
    ]
