# Generated by Django 2.1.2 on 2019-03-15 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190315_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_post_title', models.CharField(max_length=255)),
                ('group_post_body', models.TextField()),
                ('group_post_image', models.ImageField(blank=True, upload_to='group_photo')),
                ('group_post_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_comment', models.TextField()),
                ('group_comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80)),
                ('group_cover_picture', models.ImageField(blank=True, upload_to='cover_picture')),
                ('group_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 15, 3, 1, 701271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 15, 3, 1, 701271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 15, 3, 1, 701271, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_member',
            field=models.ManyToManyField(related_name='Membership', to='blog.Author'),
        ),
        migrations.AddField(
            model_name='groups',
            name='super_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='group_comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='group_comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.GroupArticle'),
        ),
        migrations.AddField(
            model_name='grouparticle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Groups'),
        ),
        migrations.AddField(
            model_name='grouparticle',
            name='group_article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='grouparticle',
            name='group_post_likes',
            field=models.ManyToManyField(blank=True, related_name='group_post_like', to='blog.Author'),
        ),
    ]
