# Generated by Django 2.1.2 on 2019-03-23 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190315_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whichgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Groups')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 5, 44, 12, 438833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 23, 5, 44, 12, 437806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 5, 44, 12, 438833, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requestgroup',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
